export const String = {
  login: 'Login',
  forget: 'Forgot Password',
  sigup: 'Sign In',
  idont: "I don't have an account",
  Please: 'Please enter your email address and an email will be sent to retrieve your password',
  Save: 'Save',
  send: 'Send',
  create: 'Create an Account',
  fullname: 'Full name',
  email: 'Email',
  Password: 'Password',
  confirmpass: 'Confirm Password',
  iagree: 'I Agree to the terms and coditions and privecy policy',
  Register: 'Register',
  alreadyhaveanaccount: 'Already have an account',
  Adrees: 'Addrees',
  upload: 'Customize service booking',
  next: 'Next',
  keep: 'Keep It Short and Simple with your heading!',
  Be: 'Be preclse with the issue in a few words.',
  examples: 'Examples :',
  Fix: 'Fix/repsair/change a leaking tap',
  install: 'Install a celling fan',
  help: 'Help deliver a cake',
  disniss: 'DISMISS',
  Welcom: 'Hello Welcome !',
  Howcan: 'How Can We Help You ?',
  sweet: 'Sweets Mithai',
  noimagefound: 'NO IMAGE FOUND',
  NonVeg: 'NonVeg',
  mikl: 'Milk Dairy',
  nasta: 'Nasta',
  Vegetables: 'Vegetables',
  Notifi: 'Notifications',
  Nodata: 'No Data Found',
  aboutus: 'About Us',
  aboutustext: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  location: 'Location',
  Add: 'Add Address',
  MYProfile: 'My Profile',
  Hello: 'Hello,',
  wlcom: 'Welcome to Home service',
  other: 'Others',
  logandsing: 'Login or Signup',
  faq: 'FAQ',
  Privacy: 'Privacy Policy',
  Terms: 'Terms & Conditions',
  How: 'How it works',
  helpcenter: 'Help Center',
  Youremail: 'Your Email',
  Describe: 'Describe',
  submit: 'Submit',
  Dianne: 'K29 Solutions',
  fddsf: 'Silver business hub, surat',
  get: 'Get Discount Up to',
  onfirst: 'On first order',
  booknow: 'Book now',
  onfirstrfd: 'On first services',
  Categories: 'Categories',
  viewad: 'View All',
  Featured: 'Featured',
  Rating: 'Rating',
  Duration: 'Duration',
  Price: 'Price',
  breathe: 'Breathe clean air. We pramptly replace fiters ensuring efficient circulation throughout your space.'
  , abiutprovi: 'About Provider',
  booking: 'Book Now',
  Bookservice: 'Book Service',
  name: 'Name',
  PhoneNumber: 'Phone Number',
  Serice: 'Service Date',
  Servicetime: 'Service Time',
  payonline: 'Pay Online',
  cashon: 'Cash on Delivery',
  bookingservice: 'Book Service',
  todat: 'Today',
  twoday: '2 Days ago',
  fiveday: '5 Days ago',
  frequ: 'Frequently Asked Questions:',
  Prenatal: 'Prenatal',
  Confidence: 'Confidence',
  Amount: 'Amount',
  FAQ: 'FAQ',
  What: 'What does Yaga mean slang?',
  does: 'What does Namaste mean?',
  can: "Can I do yoga if I'm not flexible?",
  benfit: 'Complete Bigenners should start here. This bundle will teach basic yoga posecs to fill with energy and joy. Hope on your mat and start to build......',
  yoga: 'What are the benefits of yoga?',
  disacvan: 'What are the disadvantages of yoga?',
  besttime: 'What is the best time to do yoga?',
  ConfirmandPay: 'Confirm and Pay',
  Jeanette: 'Jeanette barbershop \n professional haircut',
  youevent: "Your Events",
  Services: 'Services',
  Standart: 'Standart',
  Worker: 'Worker',
  Person: '1 Person',
  Dates: 'Dates',
  PriceDetails: 'Price Details',
  Price: 'Price',
  Appsfee: "Apps fee",
  Totalprice: "Total price",
  PaymentMethod: "Payment Method",
  MasterCard: "Master Card",
  sd: '**** **** 1234',
  payNow: 'Pay Now',
  papyall: 'Paypall',
  sascom: 'sask****@mail.com',
  addpayme: "Add Payment Method",
  ConfirmPayment: 'Confirm Payment',
  addnew: 'Add New Booking',
  // cardname: 'CardNumber',
  cardname:'Name',
  // cardHolder: 'Card Holder Name',
  cardHolder:'Address',
  // youremail: 'Your Email',
  youremail:'Your service',
  Price:'Price',
  Exprired: 'Time',
  startDate:'StartDate',
  CVV: 'CVV Code',
  addcard:'Add Bookings',
  OrderComplete:"Order Complete",
  Etiam:"Etiam cras nec metus laoreet. Faucibus iaculis cras ut posuere.",
  Viewbooking:'View Booking Service',
  discover:'Discover More Service', 
  mybookig:'MY Booking',
  allservice:"All Service",
  Acservice:'AC Service',
  plumbing:'Plumbing',
  haircut:'Jeanette barbershop professional haircut',
  ABC:'ABC Avenue. Dhaka',
  Service:'Service',
   data:'Date',
  Standart:'Standart (Person)',
   Wed:'Wed, 13 Nov 2023',
    OnGoing:'On Going',
   Canceled:'Canceled',
   Papaya:'Papaya provides all services for various AC brands',
   San:'San Diego, California',
   Categories:'Categories',
   adview:'Review',
    submit:'Submit',
    SKIP:'SKIP',
    Multiple:"Multiple Services in one App",
    ouravai:'We render quality and affordable services, select from our available services.',
    Wexxzc:'We consider your schedule, book your desired date to get service rendered.',
    Bookyour:'Book your Appointment',
    Atyour:'At your door in time',
    Yes:"Yes! we offer home services at your preferred time.",
    nameuser:'Martin Barmada (Me)',
    chats:'Chats',
    twounder:'2 Undead Massagess',
    Rise:"Rise and shine Martin, I hope you slept well 'cause I did 😄",
    Whichof:'Which of these designs do you like sir?. Mrs Celine was fine with all of them but I wanted to know...,',
    Document:'Document',
    Camera:'Camera',
    galeryy:'Gallery',
    audio:'Audio',
    location:'Location',
    Payment:'Payment',
    contact:'Contact',
    Poll:'Poll',
    rate:'Rate this product',
    rating:'Rateing :',
    Date:'Date',
    ascept:'Accept',
    reject:'Reject',
    accepted:'Accepted',
    rejected:'Rejected',







}